spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/supermarket?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      min-idle: 10
      max-active: 100
      initial-size: 20
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: update
  freemarker:
    request-context-attribute: request
    enabled: true
    cache: false
    allow-request-override: false
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true

mybatis-plus:
  type-aliases-package: com.myself.supermarket.pojo
  mapper-locations: classpath:xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
